Unlist komminarlabs pulumi-influxdb3 and pulumi-cratedb
These repos have been archived as of October 3, 2025:

- https://github.com/thulasirajkomminar/pulumi-cratedb
- https://github.com/thulasirajkomminar/pulumi-influxdb3

So this PR removes them from `package-list.json` and sets
`publisher_display: DEPRECATED` on their respective YAML files.

Note that the publisher used to be @komminarlabs but these repos in
particular were moved to the @thulasirajkomminar user. Either for that
reason or because of the archival, the `resourcedocsgen pkgversion`
command fails on CI:

```sh
 ~/Development/pulumi/registry λ ./bin/resourcedocsgen pkgversion --repoSlug komminarlabs/pulumi-createdb
Error: getting latest version for komminarlabs/pulumi-createdb: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/releases/releases#get-the-latest-release","status":"404"}
Usage:
  resourcedocsgen pkgversion [flags]

Flags:
  -h, --help              help for pkgversion
      --repoSlug string   The repository slug e.g. pulumi/pulumi-provider

Global Flags:
      --logtostderr   Log to stderr instead of to files
  -v, --verbose int   Enable verbose logging (e.g., v=3); anything >3 is very verbose

E1029 15:41:34.751964  125119 main.go:29] Failed to execute command: getting latest version for komminarlabs/pulumi-createdb: {"message":"Not Found","documentation_url":"https://docs.github.com/rest/releases/releases#get-the-latest-release","status":"404"}
```

Pinging @thulasirajkomminar as a heads up.