Don't attempt to process errors
This should address #6307. Previously, the logic for error handling on a shell-out to `npm
run test-api-docs ...` looked like this:

```javascript
const result = await exec(`npm run test-api-docs -- --pkg=${pkgMetadata.name} --split=${split} || true`);
processJSON(stdout, stderr, pkgMetadata);
```

For context, `processJSON` looks like this:

```javascript
function processJSON(stdout, stderr, pkgMetadata) {
    const contents = fs.readFileSync("ctrf/ctrf-report.json", {
        encoding: "utf8",
    });
    const results = JSON.parse(contents);

    ...
    handleAndSaveResults
    ...

    // The cli command error is trapped here since it is a sub process of this script.
    // Checking if error here will enable us to mark this as a failed run by exiting
    // unsuccessfully. Otherwise the run will always pass successfully regardless of
    // the result of the tests.
    if (stderr) {
        console.error("errors:", stderr);
        process.exit(1);
    }
}
```

I believe that this is a problem, since we still attempt to read and process the result of
failed output.

I have changed the logic to only call `processJSON` if the command was successful:

```javascript
try {
    const result = await exec(`npm run test-api-docs -- --pkg=${pkgMetadata.name} --split=${split}`);
    processJSON(stdout, stderr, pkgMetadata);
} catch (err) {
    process.exit(1);
}
```

This should fix the error we see in #6307:

```
SyntaxError: Unexpected token w in JSON at position 51948
    at JSON.parse (<anonymous>)
    at processJSON (/home/runner/work/registry/registry/scripts/run-browser-tests.js:119:26)
    at /home/runner/work/registry/registry/scripts/run-browser-tests.js:92:21
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Promise.all (index 3)
    at async processBatches (/home/runner/work/registry/registry/scripts/run-browser-tests.js:96:13)
    at async runTests (/home/runner/work/registry/registry/scripts/run-browser-tests.js:103:5)
```